=== supnge/webTest/java-test/src/main/resources/student.dtd
<?xml version="1.0" encoding="UTF-8"?>
        <!ELEMENT students (student*) >
        <!ELEMENT student (name,password,gender,birthday)>
        <!ELEMENT name (#PCDATA)>
        <!ELEMENT password (#PCDATA)>
        <!ELEMENT gender (#PCDATA)>
        <!ELEMENT birthday (#PCDATA)>
        <!ATTLIST student number ID #REQUIRED>

=== supnge/webTest/java-test/src/main/resources/student.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE students SYSTEM "student.dtd">
<students>
    <student number="S_001">
        <name>范冰冰</name>
        <password>123</password>
        <gender>女</gender>
        <birthday>1983-10-11</birthday>
    </student>
    <student number="S_002">
        <name>李冰冰</name>
        <password>123</password>
        <gender>女</gender>
        <birthday>1984-10-11</birthday>
    </student>
    <student number="S_003">
        <!-- <![CDATA[]]> 表示转义 -->
        <name><![CDATA[&glt;>林心如<]]></name>
        <password>123</password>
        <gender>女</gender>
        <birthday>1982-10-11</birthday>
    </student>
</students>
